# Generated by Django 2.0.5 on 2018-06-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-actualizado']},
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
